### ISSUE TITLE
missing required field "paths" in io.k8s.api.networking.v1.HTTPIngressRuleValue

### ISSUE THREAD

**Issue by nodesocket** [brandon099/wg-easy-helm-chart#4]
## My values file:

```yaml
persistence:
  enabled: true
  size: 1Gi

wireguard:
  host: vpn.hooli.xyz

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: vpn.hooli.xyz
      paths: []
  tls:
    - hosts:
        - vpn.hooli.xyz
```

## Install command:

```
helm install wg-easy --values values.yaml wg-easy/wg-easy
```

## Error:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http): missing required field "paths" in io.k8s.api.networking.v1.HTTPIngressRuleValue
```

**Versions:**

**Chart:** 0.1.14
**Helm:** 3.8.0
**Kubernetes:** v1.23.0

**Comment by nodesocket** [comment]
Oops. Had the wrong format for the `ingress.hosts`. This is my correct full values file:

```yaml
persistence:
  enabled: true
  size: 1Gi
  
wireguard:
  host: vpn.hooli.xyz

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: vpn.hooli.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        -  vpn.hooli.xyz
```
